### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by Jesus** [antwonlee/neck-beards#13]
Is it just me or the action to authenticate is broken?

To reproduce:

1. Sign up to create a new user.
2. Sign out.
3. Try to sign in with the credentials you've just created.

@patrick-rebel @antwonlee

**Comment by patrick-rebel** [comment]
@antwanlee is wokring on that.

**Comment by thedanotto** [comment]
At the current time, I can sign in after following your steps. Possible it's fixed. Or maybe you've forgotten your password? In that case you're screwed!

**Comment by antwonlee** [comment]
It is because user now have more validations, although I think this validation was edited by @Jesus  on username and bio.

```
  validates :bio, length: { maximum: MAX_BIO_LENGTH }
  validates :email, presence: true, uniqueness: true
  validates :full_name, presence: true
  validates :password_digest, presence: true
  validates :username, uniqueness: { case_sensitive: false, allow_blank: true }
```

**Comment by antwonlee** [comment]
This seems to be fixed already.  I am going to close it.
